# Generated by Django 6.0 on 2025-12-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='tsetmc_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
