# Generated by Django 6.0 on 2025-12-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_symbol_tsetmc_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symbol",
            name="tsetmc_id",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="ticker",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="DailyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                ("low", models.FloatField(blank=True, null=True)),
                ("close", models.FloatField(blank=True, null=True)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="core.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("symbol", "date")},
            },
        ),
        migrations.DeleteModel(
            name="DailyCandle",
        ),
    ]
